### ISSUE TITLE
Use Docker Secrets for passwords

### ISSUE THREAD

**Issue by bmschmidt** [senderle/bookworm-compose#1]
Not sure if I'm *supposed* to be able to run it... But the following lines are consistent with either a production file being improperly excluded, or me not understanding how to build those properly.

```
(base) ➜  bookworm-compose git:(main) docker-compose up          
ERROR: Couldn't find env file: /Volumes/drobo/docker/bookworm-compose/.envs/.production/.mariadb
(base) ➜  bookworm-compose git:(main) cat .envs/.gitignore 
# Ignore everything
*

# Except this file
!.gitignore
```

**Comment by senderle** [comment]
Ah, yes, excluded but intentionally, to avoid putting secrets in a public repo! Right now it's just one environment variable, the mariadb root pw. 

The file structure is

    .envs/.production/.mariadb

Inside the `.mariadb` file, put this line:

MYSQL_ROOT_PASSWORD=some_very_random_string

To be clear, the bookworm service does *not* work yet. But I think it shouldn't be difficult to make it work. Ideally there would be a way to configure the db host, user, and pw using environment variables. 

I also have to figure out how to get the routing to work. After looking into the details, I'm not sure serving the bookworm api on port 10012 is ideal, because I'd like it to live behind the SSL too. I'm sure there is a way to do that with a custom port, but I don't know what it is, and the traefik documentation is spotty. But traefik can easily route to a different path prefix.

But if it's a lot of trouble to change that in the GUI JS, then we should just serve it unencrypted.

**Comment by bmschmidt** [comment]
The gui accesses the api over port 80/443--10012 is purely for internal
use. In production I just use apache to pass queries to 10012 internally,
but nothing in JavaScript is aware that it's not a standard web port.
Should hopefully be reconciled with traefik easily.

I think it should be possible to copy that Maria conf file to the bookworm
as well and have the bookworm clients use it. Will require a couple new
lines of code in bookworm, or could populate a my.cnf file in a line of
python.

**Comment by senderle** [comment]
Aha, got it. That should be quite simple then. I had a simple flask server forwarding correctly; bookworm was giving me a bad gateway but I hadn't gotten to the point where it could connect to the db so that's probably why. This sounds good!

**Comment by bmschmidt** [comment]
Can I propose a different way to handle passwords? Seems like Docker is very fussy about optional env files--checkout the thumbs-up/thumbs-down ratio on this! https://github.com/docker/compose/pull/3955#issuecomment-341231156

So instead of using env files, populate the env variables directly using docker-compose-override.yml. (If there are ultimately more environment variables, might make sense to
allow env files, but for just one seems pointless).

Will file as a pull request. Would be happy to just take push access here.

```
services:
  bookworm:
    environment:
      - MYSQL_ROOT_PASSWORD='my_secret'
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD='my_secret'
```

**Comment by senderle** [comment]
Hmm, that post you link to seems to be about a different feature that isn't in use anymore? In the current approach (that I'm aware of) you can specify environment variables inside the `docker-compose.yml` file (as you have observed) or you can specify a separate env file for each service. I worry about putting environment variables in any `docker-compose-xyz.yml` file — even dummy ones — because it is just too close to putting secrets in a public repo. I'm probably being paranoid but if somebody gets lazy and just uses the dummy variables to set up a server, they're sitting ducks.

The really modern thing is to use a thing called docker secrets, but I don't know enough about it yet. In general, this is a situation where convenience and security are at odds with one another and I am not 100% what the best way to strike a balance is. We should talk about this on the call.

**Comment by senderle** [comment]
Btw whatever we do, we will need to document it! Apologies for omitting that initially.

**Comment by bmschmidt** [comment]
Sorry, that old link is just a discussion about allowing option env variables.

I'm working off of [this](https://github.com/bmschmidt/bookworm-compose/tree/better-passwords), with the idea that docker-compose-override be in the .gitignore while docker-compose can stay.

> By default, Compose reads two files, a docker-compose.yml and an optional docker-compose.override.yml file. By convention, the docker-compose.yml contains your base configuration. The override file, as its name implies, can contain configuration overrides for existing services or entirely new services.
> If a service is defined in both files, compose merges the configurations using the rules described in Adding and overriding configuration.

So the risk here is pretty much the same as posting into the env variables as long as [they don't actively ignore the comment here.](https://github.com/bmschmidt/bookworm-compose/blob/better-passwords/docker-compose.yml#L37-L38)

One of my reasons wanting this to have some default w/ an insecure root password is to allow automatic integration testing. 

One Q is--sitting ducks for what? An exposed MySQL root password could probably figure out how to delete the data partition (although the way that the SQL statements are passed to the server would make this tricky--I don't know how to do it!) But this is just a docker service version of MySQL. I'd be more worried if it was wordpress or something where there were user credentials. Here it's just processed data that, even on copyrighted materials, is probably free to share under Authors Guild vs Hathi Trust. Doesn't seem worthy anyone's time trying to figure out some SQL injection hack to mess with a docker container doing that.

**Comment by senderle** [comment]
Yeah I see what you mean — I'm thinking from a security best practices standpoint, but I can see that in this project we are unlikely to have additional secrets to manage.

**Comment by senderle** [comment]
As a final note, here's the documentation for docker secrets. Looking at this more closely, I think it has a lot of advantages. Two stand out:

1. It enforces a clear distinction between genetic config and security-critical information.
2. It lets you specify the location of the secret once, give it a name, and then refer to it multiple times.

For now I'm persuaded by the override approach, but in the long run I would love to be able to handle secrets this way if possible. Once we have a basic functional setup I'll return to this.

**Comment by bmschmidt** [comment]
I think this is done now.
