### ISSUE TITLE
fix `bookworm serve`

### ISSUE THREAD

**Issue by bmschmidt** [senderle/bookworm-compose#6]
I don't know why, but on my containers `bookworm serve` is not in the PATH even though this line in bookwormDB's `setup.py` ought to be activating it:

```
    entry_points={
        'console_scripts': [
            'bookworm = bookwormDB.manager:run_arguments'
        ],
    },
```

Could just activate it manually.

**Comment by senderle** [comment]
This seemed to work for me — or at least I didn't get an obvious error message indicating that the path wasn't found. But I might have missed something...

**Comment by senderle** [comment]
Aha, I see it. A subtle quirk of `command:` is that you can use a long command string, or a list containing each term of the command as an item. If you pass a list, it interprets each item as a single unit. Since you modified `docker-compose.yml` to use the list syntax, it's interpreting `bookworm serve` as a single string, and looking for an executable called `bookworm\ serve`, which obviously doesn't exist. Fix is to change

    command: 
      - bookworm serve

to

    command: bookworm serve

or 

    command: ["bookworm", "serve"]

or 

    command:
      - bookworm
      - serve

Obviously the last two make little sense in this context, but am putting them here to show the syntax.

**Comment by bmschmidt** [comment]
Oops. Thanks.
